export const SURVEY_INIT_VIEW = "SURVEY_INIT_VIEW";

export const SURVEY_ANSWER_PENDING = "SURVEY_ANSWER_PENDING";
export const SURVEY_ANSWER_FULFILED = "SURVEY_ANSWER_FULFILED";
export const SURVEY_ANSWER_REJECTED = "SURVEY_ANSWER_REJECTED";
